spring:
  application:
    name: "Trip Together API Service"
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/trip_together
    username: postgres
    password: admin
    initialization-mode: always
    schema: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: create-drop

