services:
  db:
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: trip_together
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql #schema.sql


  app:
    build: .  #Dockerfile directory
    container_name: trip_together
    environment:
      DB_HOST: db # .url in DataSourceConfig
      DB_PORT: 5432
      DB_NAME: trip_together
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data:
